DP-26179: Implement TF module with a GitHub-to-Teams webhook converter.
massgov/mds-terraform-common pull request #92
Opened 2023-02-17 23:37 UTC by DmitriiTartynovLCM

2023-02-23 17:24 UTC, chrismshelton requested changes
2 Things in the documentation, otherwise looks good to me!

2023-02-23 17:24 UTC, chrismshelton commented on webhook-converters/github-to-teams/README.md
> +The module defines a lambda function with a publicly accessible URL that accepts .
accepts what?

2023-02-23 17:24 UTC, chrismshelton commented on webhook-converters/github-to-teams/README.md
> +For example, it looks for DNS records that point to CloudFront distributions that don't exist anymore.
I think this line can be deleted?

2023-02-23 20:00 UTC, DmitriiTartynovLCM commented
@chrismshelton Thanks for catching these issues! Just updated the module description.

2023-02-24 18:53 UTC, chrismshelton approved these changes

2023-02-24 18:53 UTC, merged